/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Example API
 * Example API
 * OpenAPI spec version: 1.0
 */
import type { Option } from '../accesshandler-openapi.yml/option';
import type { Groups } from '../accesshandler-openapi.yml/groups';

export interface ArgOptions {
  /** The suggested options. */
  options: Option[];
  groups?: Groups;
}
