// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/common-fate/common-fate/pkg/api (interfaces: TargetGroupDeploymentService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	targetgroup "github.com/common-fate/common-fate/pkg/targetgroup"
	types "github.com/common-fate/common-fate/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockTargetGroupDeploymentService is a mock of TargetGroupDeploymentService interface.
type MockTargetGroupDeploymentService struct {
	ctrl     *gomock.Controller
	recorder *MockTargetGroupDeploymentServiceMockRecorder
}

// MockTargetGroupDeploymentServiceMockRecorder is the mock recorder for MockTargetGroupDeploymentService.
type MockTargetGroupDeploymentServiceMockRecorder struct {
	mock *MockTargetGroupDeploymentService
}

// NewMockTargetGroupDeploymentService creates a new mock instance.
func NewMockTargetGroupDeploymentService(ctrl *gomock.Controller) *MockTargetGroupDeploymentService {
	mock := &MockTargetGroupDeploymentService{ctrl: ctrl}
	mock.recorder = &MockTargetGroupDeploymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetGroupDeploymentService) EXPECT() *MockTargetGroupDeploymentServiceMockRecorder {
	return m.recorder
}

// CreateTargetGroupDeployment mocks base method.
func (m *MockTargetGroupDeploymentService) CreateTargetGroupDeployment(arg0 context.Context, arg1 types.CreateTargetGroupDeploymentRequest) (*targetgroup.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTargetGroupDeployment", arg0, arg1)
	ret0, _ := ret[0].(*targetgroup.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTargetGroupDeployment indicates an expected call of CreateTargetGroupDeployment.
func (mr *MockTargetGroupDeploymentServiceMockRecorder) CreateTargetGroupDeployment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTargetGroupDeployment", reflect.TypeOf((*MockTargetGroupDeploymentService)(nil).CreateTargetGroupDeployment), arg0, arg1)
}
