/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */
import type { RequestTiming } from './requestTiming';
import type { CreateRequestWithSubRequest } from './createRequestWithSubRequest';

export type CreateRequestRequestBody = {
  accessRuleId: string;
  reason?: string;
  timing: RequestTiming;
  with?: CreateRequestWithSubRequest;
};
