/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Approvals
 * Granted Approvals API
 * OpenAPI spec version: 1.0
 */

export type AccessRuleTargetDetailArgumentsFormElement = typeof AccessRuleTargetDetailArgumentsFormElement[keyof typeof AccessRuleTargetDetailArgumentsFormElement];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccessRuleTargetDetailArgumentsFormElement = {
  INPUT: 'INPUT',
  MULTISELECT: 'MULTISELECT',
  SELECT: 'SELECT',
} as const;
