/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */
import type { Grantv2 } from './grantv2';
import type { TimeConstraints } from './timeConstraints';

export interface AccessGroup {
  id: string;
  grants: Grantv2[];
  time: TimeConstraints;
  status: string;
}
