/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */
import type { ProviderGroup } from './providerGroup';

export type ArgumentGroups = {[key: string]: ProviderGroup};
