/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Approvals
 * Granted Approvals API
 * OpenAPI spec version: 1.0
 */
import type { AccessRule } from './accessRule';
import type { KeyValue } from './keyValue';

/**
 * A matched access rule with option values if they are required for the access rule request
 */
export interface LookupAccessRule {
  accessRule: AccessRule;
  /** If the matched access rule has selectable fields, this array will contain the matched values to be used to prefill the form when requesting */
  selectableWithOptionValues?: KeyValue[];
}
