/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the setup process.
 */
export type ProviderSetupStatus = typeof ProviderSetupStatus[keyof typeof ProviderSetupStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProviderSetupStatus = {
  COMPLETE: 'COMPLETE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATING: 'VALIDATING',
  INITIAL_CONFIGURATION_IN_PROGRESS: 'INITIAL_CONFIGURATION_IN_PROGRESS',
  VALIDATION_SUCEEDED: 'VALIDATION_SUCEEDED',
} as const;
