/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */

/**
 * The config values entered by the user which correspond to the setup step.
 */
export type ProviderSetupStepCompleteRequestBodyConfigValues = {[key: string]: string};
