/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */

/**
 * The status of an Access Request.

 */
export type RequestAccessGroupStatus = 'DECLINED' | 'APPROVED' | 'PENDING_APPROVAL';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestAccessGroupStatus = {
  DECLINED: 'DECLINED' as RequestAccessGroupStatus,
  APPROVED: 'APPROVED' as RequestAccessGroupStatus,
  PENDING_APPROVAL: 'PENDING_APPROVAL' as RequestAccessGroupStatus,
};
