/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Approvals
 * Granted Approvals API
 * OpenAPI spec version: 1.0
 */

/**
 * The current state of the grant.
 */
export type RequestEventFromGrantStatus = typeof RequestEventFromGrantStatus[keyof typeof RequestEventFromGrantStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestEventFromGrantStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  ERROR: 'ERROR',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
} as const;
