/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Approvals
 * Granted Approvals API
 * OpenAPI spec version: 1.0
 */

/**
 * An event which was recorded relating to the grant.
 */
export type RequestEventRecordedEvent = { [key: string]: any };
