/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Approvals
 * Granted Approvals API
 * OpenAPI spec version: 1.0
 */
import type { RequestAccessRuleDetailWith } from './requestAccessRuleDetailWith';
import type { Provider } from './provider';
import type { TimeConstraints } from './timeConstraints';

export interface RequestAccessRuleDetail {
  id: string;
  version: string;
  name: string;
  description: string;
  with: RequestAccessRuleDetailWith;
  isCurrent: boolean;
  provider: Provider;
  timeConstraints: TimeConstraints;
}
