/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */
import type { Field } from './field';

export interface Target {
  id: string;
  fields: Field[];
  accessRules: string[];
}
