/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */
import type { TimeConstraints } from './timeConstraints';
import type { TargetWith } from './targetWith';

export interface Target {
  accessRule: string;
  reason: string;
  timeConstraints: TimeConstraints;
  with: TargetWith;
}
