/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Common Fate
 * Common Fate API
 * OpenAPI spec version: 1.0
 */

export interface TargetKind {
  publisher: string;
  name: string;
  kind: string;
  icon: string;
}
