package eksrolessso

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/iam"
	iamtypes "github.com/aws/aws-sdk-go-v2/service/iam/types"
	"github.com/aws/aws-sdk-go-v2/service/identitystore"
	idtypes "github.com/aws/aws-sdk-go-v2/service/identitystore/types"

	"github.com/aws/aws-sdk-go-v2/service/ssoadmin"
	"github.com/aws/aws-sdk-go-v2/service/ssoadmin/types"
	"github.com/common-fate/granted-approvals/pkg/cfaws/policy"
	"github.com/pkg/errors"
	"github.com/sethvargo/go-retry"
	"gopkg.in/yaml.v2"
	v1 "k8s.io/api/rbac/v1"
	v1meta "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type Args struct {
	Role string `json:"role" jsonschema:"title=Role"`
}

func (p *Provider) Grant(ctx context.Context, subject string, args []byte, grantID string) error {
	var a Args
	err := json.Unmarshal(args, &a)
	if err != nil {
		return err
	}

	key := fmt.Sprintf("granted-approvals-%s", grantID)

	// // @TODO work out what aws permissions are actually required for cluster access
	eksPolicyDocument := policy.Policy{
		Version: "2012-10-17",
		Statements: []policy.Statement{
			{
				Effect: "Allow",
				Action: []string{
					"eks:AccessKubernetesApi",
				},
				Resource: []string{fmt.Sprintf("arn:aws:eks:%s:%s:cluster/%s", p.clusterRegion.Get(), p.awsAccountID, p.clusterName.Get())},
			},
		},
	}

	// Permission set names have a maximum length of 32, in normal use a KSUID will be the grant ID so this shoudl never get truncated
	permissionSetName := grantID
	if len(permissionSetName) > 32 {
		permissionSetName = permissionSetName[:32]
	}

	// create permission set with policy
	permSet, err := p.ssoClient.CreatePermissionSet(ctx, &ssoadmin.CreatePermissionSetInput{
		InstanceArn: aws.String(p.instanceARN.Get()),
		Name:        aws.String(permissionSetName),
		Description: aws.String("This permission set was automatically generated by Granted Approvals"),
	})
	if err != nil {
		return err
	}
	// Assign eks policy to permission set
	_, err = p.ssoClient.PutInlinePolicyToPermissionSet(ctx, &ssoadmin.PutInlinePolicyToPermissionSetInput{
		InlinePolicy:     aws.String(eksPolicyDocument.String()),
		InstanceArn:      aws.String(p.instanceARN.Get()),
		PermissionSetArn: permSet.PermissionSet.PermissionSetArn,
	})
	if err != nil {
		return err
	}

	// assign user to permission set

	// find the user ID from the provided email address.
	user, err := p.getUser(ctx, subject)
	if err != nil {
		return err
	}

	res, err := p.ssoClient.CreateAccountAssignment(ctx, &ssoadmin.CreateAccountAssignmentInput{
		InstanceArn:      aws.String(p.instanceARN.Get()),
		PermissionSetArn: permSet.PermissionSet.PermissionSetArn,
		PrincipalType:    types.PrincipalTypeUser,
		PrincipalId:      user.UserId,
		TargetId:         &p.awsAccountID,
		TargetType:       types.TargetTypeAwsAccount,
	})
	if err != nil {
		return err
	}

	if res.AccountAssignmentCreationStatus.FailureReason != nil {
		return fmt.Errorf("failed creating account assignment: %s", *res.AccountAssignmentCreationStatus.FailureReason)
	}
	role, err := p.GetIAMRoleForPermissionSetWithRetry(ctx, permissionSetName)
	if err != nil {
		return err
	}
	_ = role

	// create a kubernetes role-binding for subject to the kubernetes role

	rb := v1.RoleBinding{
		TypeMeta: v1meta.TypeMeta{Kind: "RoleBinding", APIVersion: "rbac.authorization.k8s.io/v1"},
		// use the key for the name
		ObjectMeta: v1meta.ObjectMeta{Name: key},
		// use the key as the user too
		Subjects: []v1.Subject{{Kind: "User", APIGroup: "rbac.authorization.k8s.io", Name: key, Namespace: p.namespace.Get()}},
		RoleRef:  v1.RoleRef{APIGroup: "rbac.authorization.k8s.io", Kind: "Role", Name: a.Role},
	}
	r, err := p.kubeClient.RbacV1().RoleBindings(p.namespace.Get()).Create(ctx, &rb, v1meta.CreateOptions{})
	if err != nil {
		return err
	}
	_ = r
	awsAuth, err := p.kubeClient.CoreV1().ConfigMaps("kube-system").Get(ctx, "aws-auth", v1meta.GetOptions{})
	if err != nil {
		return err
	}

	type MapRoleEntry struct {
		RoleARN  *string `yaml:"rolearn,omitempty"`
		Username *string `yaml:"username,omitempty"`
	}
	var dc []interface{}
	err = yaml.NewDecoder(bytes.NewBufferString(awsAuth.Data["mapRoles"])).Decode(&dc)
	if err != nil {
		return err
	}

	substringToRemove := fmt.Sprintf("aws-reserved/sso.amazonaws.com/%s/", p.ssoRegion.Get())
	cleanedRoleArn := strings.Replace(*role.Arn, substringToRemove, "", 1)
	dc = append(dc, MapRoleEntry{RoleARN: aws.String(cleanedRoleArn), Username: aws.String(key)})
	var buf bytes.Buffer
	err = yaml.NewEncoder(&buf).Encode(dc)
	if err != nil {
		return err
	}
	awsAuth.Data["mapRoles"] = buf.String()

	out, err := p.kubeClient.CoreV1().ConfigMaps("kube-system").Update(ctx, awsAuth, v1meta.UpdateOptions{})
	if err != nil {
		return err
	}
	_ = out
	return nil
}

func (p *Provider) GetIAMRoleForPermissionSetWithRetry(ctx context.Context, permissionSetName string) (*iamtypes.Role, error) {
	var roleOutput *iamtypes.Role
	b := retry.NewFibonacci(time.Second)
	b = retry.WithMaxDuration(time.Second*60, b)
	err := retry.Do(ctx, b, func(ctx context.Context) (err error) {
		var marker *string
		hasMore := true

		ssoPathPrefix := "/aws-reserved/sso.amazonaws.com/ap-southeast-2/"
		roleNamePrefix := "AWSReservedSSO_" + permissionSetName
		for hasMore {
			listRolesResponse, err := p.iamClient.ListRoles(ctx, &iam.ListRolesInput{PathPrefix: aws.String(ssoPathPrefix), Marker: marker})
			if err != nil {
				return retry.RetryableError(err)
			}
			marker = listRolesResponse.Marker
			hasMore = listRolesResponse.IsTruncated
			for _, role := range listRolesResponse.Roles {
				if strings.HasPrefix(aws.ToString(role.RoleName), roleNamePrefix) {
					r := role
					roleOutput = &r
				}
			}
		}
		if roleOutput == nil {
			return retry.RetryableError(errors.New("role not yet available or does not exist"))
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if roleOutput == nil {
		return nil, errors.New("role not found after assiging permission set")
	}

	return roleOutput, nil
}

// getUser retrieves the AWS SSO user from a provided email address.
func (p *Provider) getUser(ctx context.Context, email string) (*idtypes.User, error) {
	res, err := p.idStoreClient.ListUsers(ctx, &identitystore.ListUsersInput{
		IdentityStoreId: aws.String(p.identityStoreID.Get()),
		Filters: []idtypes.Filter{{
			AttributePath:  aws.String("UserName"),
			AttributeValue: aws.String(email),
		}},
	})
	if err != nil {
		return nil, err
	}
	if len(res.Users) == 0 {
		return nil, &UserNotFoundError{Email: email}
	}
	if len(res.Users) > 1 {
		// this should never happen, but check it anyway.
		return nil, fmt.Errorf("expected 1 user but found %v", len(res.Users))
	}

	return &res.Users[0], nil
}
func (p *Provider) Revoke(ctx context.Context, subject string, args []byte, grantID string) error {
	var a Args
	err := json.Unmarshal(args, &a)
	if err != nil {
		return err
	}

	// reverse the process from grant step

	return err
}

func (p *Provider) IsActive(ctx context.Context, subject string, args []byte, grantID string) (bool, error) {
	var a Args
	err := json.Unmarshal(args, &a)
	if err != nil {
		return false, err
	}

	// we didn't find the user, so return false.
	return false, nil
}
