// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package types

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// DeploymentResponse defines model for DeploymentResponse.
type DeploymentResponse struct {
	StackId string `json:"stackId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// DeploymentRequest defines model for DeploymentRequest.
type DeploymentRequest struct {
	Name    string  `json:"name"`
	StackId *string `json:"stackId,omitempty"`
	Team    string  `json:"team"`
	Version string  `json:"version"`
}

// DeleteDeploymentJSONBody defines parameters for DeleteDeployment.
type DeleteDeploymentJSONBody = string

// DeleteDeploymentJSONRequestBody defines body for DeleteDeployment for application/json ContentType.
type DeleteDeploymentJSONRequestBody = DeleteDeploymentJSONBody

// PostDeploymentJSONRequestBody defines body for PostDeployment for application/json ContentType.
type PostDeploymentJSONRequestBody DeploymentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /api/v1/deployments)
	DeleteDeployment(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/deployments)
	PostDeployment(w http.ResponseWriter, r *http.Request)
	// Your GET endpoint
	// (GET /api/v1/secrets)
	GetSecret(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/secrets)
	PostSecret(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// DeleteDeployment operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeployment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeployment(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostDeployment operation middleware
func (siw *ServerInterfaceWrapper) PostDeployment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDeployment(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSecret operation middleware
func (siw *ServerInterfaceWrapper) GetSecret(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSecret(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostSecret operation middleware
func (siw *ServerInterfaceWrapper) PostSecret(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSecret(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/deployments", wrapper.DeleteDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/deployments", wrapper.PostDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/secrets", wrapper.GetSecret)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/secrets", wrapper.PostSecret)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUy27cOgz9FYH3Lo2R067qXZqkQdBFB203RZCFYnNmlFqiStFBBwP/eyF5nrHTIGi8",
	"sUDxcc4RyQ3U5AJ59BKh2gDjrw6jfKTGYjZcYmhp7dDL1+EqGWvygj4fTQitrY1Y8vohkk+2WK/QmXQK",
	"TAFZtrm8cZj+sg4IFURh65fQFxDF1D9vmsk7QeMmLx6Rox0KPrnri8zDMjZQ3Q4ZiqH6Ieyu2IXR/QPW",
	"An36UmQM5OOY/WD+B/rPs3wCeOc4BbGABmPNNkjmDle/jQstqh3spMwVM/EbAMaUZxrui7jOvcrhilE6",
	"9tioBZNTskJ1Pr+ZDSHWL2iHz9Ry6BG4IOfIq09G0pt13EIFK5EQK63rfLcwgjNL8Kwi5/MbKECstDiy",
	"7nsHzmZlSkEBvQkWKng/K2clFBCMrLIK2gSrH890s++FbG6wRcHhdFz+MtuVUQd/yPk5i57ef+tzeexw",
	"GLz1q17stHiSN3ePso0SUveoBpwNFKNXHHX7u7JMv/8ZF1DBf/qwGvTeT0+MRM4UaNgNp4AuGI2gIlZd",
	"aMxLuswpyt9UmUZ2tLH0eF29Icm+2DdDxJpxaIQlZt6nTK5RvmUXmC5/qtKXz3moYuec4TVU8IM6VtdX",
	"3xX6JpD1mcZO4bFmry2VqUTkNAZQ3W6OBqzSuqXatCuKUn0oyxL6tIbMcnDcjueSTRqDvthbuPNiHUJ/",
	"1/8JAAD//6pescBUBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
