/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Example API
 * Example API
 * OpenAPI spec version: 1.0
 */

export type CreateGroupRequestBody = {
  name: string;
  description?: string;
  members: string[];
};
