/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Example API
 * Example API
 * OpenAPI spec version: 1.0
 */
import type { CreateRequestWithSubRequest } from '../openapi.yml/createRequestWithSubRequest';
import type { RequestTiming } from '../openapi.yml/requestTiming';

/**
 * Detailed object for a Favorite. 
 */
export interface FavoriteDetail {
  id: string;
  name: string;
  with: CreateRequestWithSubRequest;
  reason?: string;
  timing: RequestTiming;
}
