/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Example API
 * Example API
 * OpenAPI spec version: 1.0
 */
import type { Favorite } from './favorite';

export type ListFavoritesResponseResponse = {
  next: string | null;
  favorites: Favorite[];
};
