/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Example API
 * Example API
 * OpenAPI spec version: 1.0
 */
import type { User } from '../openapi.yml/user';

export type ListUserResponseResponse = {
  users: User[];
  next: string | null;
};
